### PR TITLE
Makes json for moc server 

### PR DESCRIPTION
**Pull request by CarlFK**
```
litex-renode$ python3 generate-renode-scripts.py ~/temp/csr.csv  --json-file x.json
  "hdmi": {
    "in": [
      {
        "chansync": {
          "channels": {
            "synced": {
              "size": "1",
              "name": "hdmi_in0_chansync_channels_synced",
              "address": "0xe000b0a8",
              "r": "ro"
            }
          }
        },
        "dma": {
          "ev": {
            "enable": {
              "size": "1",
              "name": "hdmi_in0_dma_ev_enable",
              "address": "0xe000b100",
              "r": "rw"
            },
            "status": {
              "size": "1",
              "name": "hdmi_in0_dma_ev_status",
              "address": "0xe000b0f8",
```

### CODE REVIEW

**Comment by mateusz-holenko** [comment]
Thanks for your contribution!

Could you describe a bit more what moc server is and how is it related to LiteX?

I'm asking, because `litex-renode` repository and `generate-renode-scripts.py` file are currently strictly related to [Renode](https://renode.io).
In this context adding `--json-file` for moc server is a bit questionable to me.

I understand that you use part of parsing logic from the current script, so it's easier to put the new code there.
I would suggest however creating a new script, say `generate-moc-json.py`, and extract the common logic to `litex-config-lib.py`.

This way the distinction between the parser and two separate generators would be obvious.

The next step would be to rename the repository to, e.g., `litex-config-parsers` and make it host other generators as well - including Linux DTS.

@mithro What do you think about it?

**Comment by CarlFK** [comment]
HDMI2USB - we would like a nice ui to view status/debug data: a desktop computer / browser / js that consumes some json and displays it in a nice format. 

To aid development of the .js, the generated .json is to be served by https://github.com/CarlFK/HDMI2USB-litex-firmware/blob/master/mocserver/moc-server.py   - doesn't require the hdmi2usb side to exist.

"nice format"=organized based on knowing something about the data.   Which kinda ties this to hdmi2usb project, but maybe this can be used for other projects too?

I'll split it up into different files.

**Comment by CarlFK** [comment]
I don't see a good way to split this up.  

mainly because I don't see a good place for these 2 things:

the global/module vars:

     20 non_generated_mem_regions = ['ethmac', 'spiflash', 'csr']
     21 
     22 mem_regions = {}
     23 peripherals = {}
     24 registers = {}
     25 constants = {}

everything needs this command line arg:
```
    623     parser.add_argument('conf_file',
    624                         help='CSV configuration generated by LiteX')
```
If there was an abstract class with the vars as attributes and the hooks for more  parser.add_argument, then sure.    But that seems like a bit of work and the results will be harder to understand for the current cases.  


this makes me cringe:
```
import lib
...
lib.mem_regions[foo]=bar
...
f.write(lib.mem_regions[foo])
```
lib shouldn't be where values are stored.  I think.

**Comment by mateusz-holenko** [comment]
I'll take a look at refactoring the script a bit, so that's easy to extact the parsing part from it.

**Comment by CarlFK** [comment]
Before you do any work on this, I just had some thoughts:

The point of this is to moc what HDMI2USB produces.  Once HDMI2USB produces something, we can just grab a copy of that and won't need this code any more. 

There is a chance something else may need 'this', but I bet that part of HDMI2USB producing json will be code to generate something json like which will take the place of this code.

**Comment by mateusz-holenko** [comment]
I agree that having values stored as globals in library scope is not the most beautiful approach.

I pushed my idea here: https://github.com/antmicro/litex-renode/blob/extract_lib/litex/configuration.py.

I simply extracted parsing code to a separate file and wrapped it around a class that holds both parsing logic and the parsed values.  As a result only minmal changes to the scirpt are needed to make it work. The example usage of the new `Configuration` class: https://github.com/antmicro/litex-renode/blob/extract_lib/generate-renode-scripts.py#L509.

@CarlFK What do you think about this approach?

**Comment by CarlFK** [comment]
Looks ok, but I think you should accept my PR, then refactor so that the lib has the extra 
registers = {} and parser in it.

**Comment by mateusz-holenko** [comment]
Thanks!

I pushed some commits on top:
* 2bb663fdbe47057cb7656ece6af0baa41c3261d2 - extracting the common parsing code,
* dcd3fd869cfe8f2e9a30f797400b93e2889ce61c - extracting mocserver script

**Pull request merged**
